### PR TITLE
Remove dynamic imports

### PR DESCRIPTION
**Pull request by bohjak**
Based on suggestion from @TomiTakussaari (https://github.com/spring-media/aws-lambda-router/issues/65).

I kept the dynamic require as a fall back since the `handler` tests are basically built around the ability to easily mock a processor and it shouldn't interfere with the main goal of making the library work with esbuild.

### CODE REVIEW

**Comment by chgohlke** [comment]
Hi @jamesbohacek, thanks for your PR. Can you please add a small test that tests the new functionality? A thanks in advance :blush:

**Comment by Chansen88** [comment]
This would be very helpful for me due to issues with esbuild.

**Comment by givethemheller** [comment]
> This would be very helpful for me due to issues with esbuild.

What issues are you having with ESBuild right now? I've just setup and I am getting a warning when I try to execute my lambda. Note, I am using typescript
```
"Error: The event processor 'proxyIntegration', that is mentioned in the routerConfig, cannot be instantiated (Error: Cannot find module './lib/proxyIntegration'
```

**Comment by givethemheller** [comment]
@chgohlke I can confirm that this fixed issues with me using a standard esbuild as prescribed by AWS documentation.

Without the fix, I was receiving the error above and I am now properly executing. Can this get merged?

**Comment by Xavier59** [comment]
Bump. Same error there, and esbuild is the recommended way to bundle typescript as per AWS documentation.

**Comment by bohjak** [comment]
Seems I kinda forgot about this PR :sweat_smile: 
I'm no longer using this library and don't have time to spend on this.

So, I'll close this PR, but anybody interested is welcome to copy/adapt/improve it and make a new PR. The code is mostly taken from @TomiTakussaari's issue anyway.

**Pull request closed without merging**
