### PR TITLE
Allow for custom status codes from route

### PR DESCRIPTION
**Pull request by mintuz**
Hello 👋 

We (Booking.com) have been experimenting with routing in Lambdas and have been using your library as a basis. As one of our requirements we need the ability to override the default statusCode of 200 with other codes depending on the execution of the lambda route. This PR is to enable that functionality.

## How it works
It still supports the default way of working where you can just return an object and it'll be returned within the response of the lambda. 

However we've added extra functionality where if a key of body exists on the returned object, It will allow for the raw lambda response to be returned within the response object. For example

```
module.exports = (request) {
    return {
        headers: {
            'x-fake-header': 'fake-value'
        },
        statusCode: 201,
        body: JSON.stringify({foo:'bar'})
    };
}
```

### CODE REVIEW

**Comment by jzlai** [comment]
Hi,
thanks for this amazing PR. It would be great if you could also provide some documentation and update the README accordingly. Thanks!

**Comment by mintuz** [comment]
@jzlai hey the README has now been updated 😄 glad you like it.

**Comment by jzlai** [comment]
Thanks again @mintuz 👍. We are also gonna publish this version to npm soon so you can use the npm package.

**Comment by mintuz** [comment]
Hey @jzlai can you mention me on this thread when it has been published, we are pointing to our fork atm so it would be good to be aligned to the public npm registry again 😄

**Pull request merged**
